### ISSUE TITLE
Feather 32u4 interrupt

### ISSUE THREAD

**Issue by FrancoisCosta** [paulvangentcom/heartrate_analysis_Arduino#2]
Hi Paul,

I was wondering what I should change the timer interrupt values to when using the Feather 32u4 rather than the Uno as it does not use the 328p. 

<img width="275" alt="Screenshot 2019-04-18 at 15 31 39" src="https://user-images.githubusercontent.com/39350856/56364553-180b9100-61ef-11e9-87a5-1ddce02a5fe1.png">

Thanks!
Francois

**Comment by FrancoisCosta** [comment]
Also, does the SimpleLogger_Scaling_AVR_USB.ino sketch have a version where the data is collected on an SD card rather than over USB? I was not able to find it.

**Comment by FrancoisCosta** [comment]
UPDATE - found the Simple Logger SD card sketch in the experimental folder (apologies!) 
However it is limited to 250Hz - any chance I could sample at 1kHz?

**Comment by paulvangentcom** [comment]
Do note that the SD logger is not stable. On my end it hangs after a variable time (30 min up to 12 hours until it happens). This is why there is a note is in the documentation saying this

**Comment by paulvangentcom** [comment]
Did you try with the current registry values? Odds are they don't differ on the 32u4. Otherwise let me know and I'll tell you where to look in the datasheet

**Comment by FrancoisCosta** [comment]
RE the SD logger - ah that's a shame! I was hoping to use the SD card function until the Wi-Fi data transfer compatibility is implemented.. However, if that could be done this weekend then I'll just wait. 
 
I'll try the current registry values and let you know how it goes! 

Francois

**Comment by FrancoisCosta** [comment]
Hi Paul,
I'm a bit confused as to how I should check whether the data collected using the current registry values on the 32u4 is correct. I was able to collect some data, and the python analysis showed reasonable values including 62 HR but I'm not sure how to check whether the interrupt was set up correctly.

**Comment by paulvangentcom** [comment]
Hi Francois,

If data is being reported, the interrupts work. Without interrupts, no data collection is triggered.

The only question that remains is what CPU speed you use, 8 or 16MHz.

**Comment by paulvangentcom** [comment]
Sorry, never mind, I see I already implemented the code to retrieve the CPU speed and calculate the interrupt timer values accordingly!

If it logs, you don't need to do anything else
